stages:
  - renovate

run-renovate:
  image: renovate/renovate:latest
  stage: renovate
  script:
    - renovate
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
  variables:
    RENOVATE_TOKEN: $RENOVATE_TOKEN
    LOG_LEVEL: "debug" 


