require: rubocop-rails

AllCops:
  NewCops: enable
  SuggestExtensions: false

Style/Documentation:
  Enabled: false

Metrics/ClassLength:
  Max: 500

Metrics/MethodLength:
  Max: 50

Metrics/AbcSize:
  Max: 60

Metrics/CyclomaticComplexity:
  Max: 20

Metrics/PerceivedComplexity:
  Max: 20

Rails/I18nLocaleTexts:
  Enabled: false

Rails/UniqueValidationWithoutIndex:
  Enabled: false

Rails/ThreeStateBooleanColumn:
  Enabled: false

Rails/BulkChangeTable:
  Enabled: false

Style/SafeNavigationChainLength:
  Enabled: false

Layout/LineLength:
  Max: 150

Metrics/BlockLength:
  Enabled: false
